- id: doi:10.1101/2024.02.26.24303069
  type: paper
  description: We identified sparse networks of proteins associated with FEV1, emphysema, and smoking status in the COPDGene study. We performed genome-wide association studies on summary measures of these networks. 
  date: 2024-02-28
  image: https://www.medrxiv.org/content/medrxiv/early/2024/02/28/2024.02.26.24303069/F5.large.jpg
  tags:
    - proteomics
    - networks
    - genetics
